; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 -stop-after=finalize-isel -o - %s | FileCheck -check-prefix=DAG %s
; RUN: llc -global-isel -mtriple=amdgcn -mcpu=gfx900 -stop-after=instruction-select -o - %s | FileCheck -check-prefix=GISEL %s

; Check that the MachineMemOperands describing the load from the global/buffer
; address space and the store into LDS survive instruction selection, and that
; SelectionDAG and GlobalISel agree on them.

define amdgpu_ps void @buffer_load_lds(ptr addrspace(8) inreg %src, ptr addrspace(3) inreg %dst) {
  ; DAG-LABEL: name: buffer_load_lds
  ; DAG: bb.0 (%ir-block.0):
  ; DAG-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4
  ; DAG-NEXT: {{  $}}
  ; DAG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr4
  ; DAG-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr3
  ; DAG-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; DAG-NEXT:   [[COPY3:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; DAG-NEXT:   [[COPY4:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; DAG-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:sgpr_64 = REG_SEQUENCE [[COPY2]], %subreg.sub0, [[COPY1]], %subreg.sub1
  ; DAG-NEXT:   [[COPY5:%[0-9]+]]:sreg_32 = COPY [[REG_SEQUENCE]].sub1
  ; DAG-NEXT:   [[COPY6:%[0-9]+]]:sreg_32 = COPY [[REG_SEQUENCE]].sub0
  ; DAG-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:sgpr_64 = REG_SEQUENCE [[COPY4]], %subreg.sub0, [[COPY3]], %subreg.sub1
  ; DAG-NEXT:   [[COPY7:%[0-9]+]]:sreg_32 = COPY [[REG_SEQUENCE1]].sub1
  ; DAG-NEXT:   [[COPY8:%[0-9]+]]:sreg_32 = COPY [[REG_SEQUENCE1]].sub0
  ; DAG-NEXT:   [[REG_SEQUENCE2:%[0-9]+]]:sgpr_128 = REG_SEQUENCE killed [[COPY8]], %subreg.sub0, killed [[COPY7]], %subreg.sub1, killed [[COPY6]], %subreg.sub2, killed [[COPY5]], %subreg.sub3
  ; DAG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; DAG-NEXT:   $m0 = COPY [[COPY]]
  ; DAG-NEXT:   BUFFER_LOAD_DWORD_LDS_OFFSET killed [[REG_SEQUENCE2]], killed [[S_MOV_B32_]], 16, 0, 0, 0, implicit $exec, implicit $m0 :: (dereferenceable load (s32) from %ir.src, align 1, addrspace 8), (dereferenceable store (s2048) into %ir.dst + 16, align 1, addrspace 3)
  ; DAG-NEXT:   S_ENDPGM 0
  ;
  ; GISEL-LABEL: name: buffer_load_lds
  ; GISEL: bb.1 (%ir-block.0):
  ; GISEL-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; GISEL-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY $sgpr1
  ; GISEL-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $sgpr2
  ; GISEL-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $sgpr3
  ; GISEL-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:sgpr_128 = REG_SEQUENCE [[COPY]], %subreg.sub0, [[COPY1]], %subreg.sub1, [[COPY2]], %subreg.sub2, [[COPY3]], %subreg.sub3
  ; GISEL-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY $sgpr4
  ; GISEL-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; GISEL-NEXT:   $m0 = COPY [[COPY4]]
  ; GISEL-NEXT:   BUFFER_LOAD_DWORD_LDS_OFFSET [[REG_SEQUENCE]], [[S_MOV_B32_]], 16, 0, 0, 0, implicit $exec, implicit $m0 :: (dereferenceable load (i32) from %ir.src, align 1, addrspace 8), (dereferenceable store (s2048) into %ir.dst + 16, align 1, addrspace 3)
  ; GISEL-NEXT:   S_ENDPGM 0
  call void @llvm.amdgcn.raw.ptr.buffer.load.lds(
      ptr addrspace(8) %src, ptr addrspace(3) %dst,
      i32 4, i32 0, i32 0, i32 16, i32 0)
  ret void
}

define amdgpu_ps void @global_load_lds(ptr addrspace(1) %src, ptr addrspace(3) inreg %dst) {
  ; DAG-LABEL: name: global_load_lds
  ; DAG: bb.0 (%ir-block.0):
  ; DAG-NEXT:   liveins: $vgpr0, $vgpr1, $sgpr0
  ; DAG-NEXT: {{  $}}
  ; DAG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; DAG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; DAG-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; DAG-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[COPY2]], %subreg.sub0, [[COPY1]], %subreg.sub1
  ; DAG-NEXT:   $m0 = COPY [[COPY]]
  ; DAG-NEXT:   [[COPY3:%[0-9]+]]:vreg_64 = COPY [[REG_SEQUENCE]]
  ; DAG-NEXT:   GLOBAL_LOAD_LDS_DWORD killed [[COPY3]], 16, 0, 0, implicit $m0, implicit $exec :: (load (s32) from %ir.src + 16, align 1, addrspace 1), (store (s2048) into %ir.dst + 16, align 1, addrspace 3)
  ; DAG-NEXT:   S_ENDPGM 0
  ;
  ; GISEL-LABEL: name: global_load_lds
  ; GISEL: bb.1 (%ir-block.0):
  ; GISEL-NEXT:   liveins: $sgpr0, $vgpr0, $vgpr1
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GISEL-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GISEL-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[COPY]], %subreg.sub0, [[COPY1]], %subreg.sub1
  ; GISEL-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; GISEL-NEXT:   $m0 = COPY [[COPY2]]
  ; GISEL-NEXT:   GLOBAL_LOAD_LDS_DWORD [[REG_SEQUENCE]], 16, 0, 0, implicit $m0, implicit $exec :: (load (i32) from %ir.src + 16, align 1, addrspace 1), (store (s2048) into %ir.dst + 16, align 1, addrspace 3)
  ; GISEL-NEXT:   S_ENDPGM 0
  call void @llvm.amdgcn.global.load.lds(
      ptr addrspace(1) %src, ptr addrspace(3) %dst,
      i32 4, i32 16, i32 0)
  ret void
}
