; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='print<scalar-evolution>,loop-unroll' -verify-scev -S < %s 2>/dev/null | FileCheck %s

; SCEV can look through the trivial LCSSA phi feeding %iv.start via the
; extractvalue of a with.overflow intrinsic, caching a SCEV that uses the
; loaded value defined in %loop1. When %loop1 is peeled and a predecessor is
; added to the (aggregate-typed) LCSSA phi, that cached SCEV becomes stale.
; forgetLcssaPhiWithNewPredecessor must invalidate it even though the phi
; itself is not SCEVable, otherwise the start value of %loop2 is no longer
; available at the loop entry and getAddRecExpr asserts. See issue #200858.

define void @f8() {
; CHECK-LABEL: define void @f8() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP1_PEEL_BEGIN:.*]]
; CHECK:       [[LOOP1_PEEL_BEGIN]]:
; CHECK-NEXT:    br label %[[LOOP1_PEEL:.*]]
; CHECK:       [[LOOP1_PEEL]]:
; CHECK-NEXT:    [[LD_PEEL:%.*]] = load i64, ptr null, align 8
; CHECK-NEXT:    [[OV_PEEL:%.*]] = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 0, i64 [[LD_PEEL]])
; CHECK-NEXT:    br i1 true, label %[[LOOP1_PEEL_NEXT:.*]], label %[[IF_END:.*]]
; CHECK:       [[LOOP1_PEEL_NEXT]]:
; CHECK-NEXT:    br label %[[LOOP1_PEEL_BEGIN2:.*]]
; CHECK:       [[LOOP1_PEEL_BEGIN2]]:
; CHECK-NEXT:    br label %[[ENTRY_PEEL_NEWPH:.*]]
; CHECK:       [[ENTRY_PEEL_NEWPH]]:
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[LD:%.*]] = load i64, ptr null, align 8
; CHECK-NEXT:    [[OV:%.*]] = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 0, i64 [[LD]])
; CHECK-NEXT:    br i1 true, label %[[LOOP1]], label %[[IF_END_LOOPEXIT:.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[IF_END_LOOPEXIT]]:
; CHECK-NEXT:    [[OV_LCSSA_PH:%.*]] = phi { i64, i1 } [ [[OV]], %[[LOOP1]] ]
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[OV_MERGE:%.*]] = phi { i64, i1 } [ [[OV_PEEL]], %[[LOOP1_PEEL]] ], [ [[OV_LCSSA_PH]], %[[IF_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[IV_START:%.*]] = extractvalue { i64, i1 } [[OV_MERGE]], 0
; CHECK-NEXT:    br label %[[LOOP2_PEEL_BEGIN:.*]]
; CHECK:       [[LOOP2_PEEL_BEGIN]]:
; CHECK-NEXT:    br label %[[LOOP2_PEEL:.*]]
; CHECK:       [[LOOP2_PEEL]]:
; CHECK-NEXT:    [[IV_NEXT_PEEL:%.*]] = add i64 [[IV_START]], 1
; CHECK-NEXT:    br label %[[LOOP2_PEEL_NEXT:.*]]
; CHECK:       [[LOOP2_PEEL_NEXT]]:
; CHECK-NEXT:    br label %[[LOOP2_PEEL_NEXT2:.*]]
; CHECK:       [[LOOP2_PEEL_NEXT2]]:
; CHECK-NEXT:    br label %[[IF_END_PEEL_NEWPH:.*]]
; CHECK:       [[IF_END_PEEL_NEWPH]]:
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], %[[LOOP2]] ], [ [[IV_NEXT_PEEL]], %[[IF_END_PEEL_NEWPH]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    br label %[[LOOP2]], !llvm.loop [[LOOP2:![0-9]+]]
;
entry:
  br label %loop1

loop1:                                             ; preds = %loop1, %entry
  %iv1 = phi i64 [ 0, %loop1 ], [ 1, %entry ]
  %ld = load i64, ptr null, align 8
  %ov = call { i64, i1 } @llvm.uadd.with.overflow.i64(i64 0, i64 %ld)
  br i1 true, label %loop1, label %if.end

if.end:                                            ; preds = %loop1
  %iv.start = extractvalue { i64, i1 } %ov, 0
  br label %loop2

loop2:                                             ; preds = %loop2, %if.end
  %flag = phi i8 [ 1, %loop2 ], [ 0, %if.end ]
  %iv = phi i64 [ %iv.next, %loop2 ], [ %iv.start, %if.end ]
  %iv.next = add i64 %iv, 1
  br label %loop2
}

declare { i64, i1 } @llvm.uadd.with.overflow.i64(i64, i64)
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.peeled.count", i32 1}
; CHECK: [[LOOP2]] = distinct !{[[LOOP2]], [[META1]]}
;.
