; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=separate-const-offset-from-gep < %s | FileCheck %s

target datalayout = "p100:128:64:64"

; Covers splitGEP's initial addressing mode check.
define void @test1(ptr addrspace(100) %P, i128 %i) {
; CHECK-LABEL: define void @test1(
; CHECK-SAME: ptr addrspace(100) [[P:%.*]], i128 [[I:%.*]]) {
; CHECK-NEXT:    [[I70:%.*]] = add i128 [[I]], 1180591620717411303424
; CHECK-NEXT:    [[I69:%.*]] = add i128 [[I]], 590295810358705651712
; CHECK-NEXT:    [[A:%.*]] = getelementptr double, ptr addrspace(100) [[P]], i128 [[I70]]
; CHECK-NEXT:    [[B:%.*]] = getelementptr double, ptr addrspace(100) [[P]], i128 [[I69]]
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr addrspace(100) [[A]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr addrspace(100) [[B]], align 8
; CHECK-NEXT:    ret void
;
  %i70 = add i128 %i, 1180591620717411303424
  %i69 = add i128 %i, 590295810358705651712
  %A = getelementptr double, ptr addrspace(100) %P, i128 %i70
  %B = getelementptr double, ptr addrspace(100) %P, i128 %i69
  load double, ptr addrspace(100) %A
  load double, ptr addrspace(100) %B
  ret void
}

; Covers splitGEP's retry without the extracted base offset.
define ptr addrspace(100) @split_overwide_offset_after_base_fallback(ptr addrspace(100) %P, i128 %i) {
; CHECK-LABEL: define ptr addrspace(100) @split_overwide_offset_after_base_fallback(
; CHECK-SAME: ptr addrspace(100) [[P:%.*]], i128 [[I:%.*]]) {
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr i8, ptr addrspace(100) [[P]], i128 -9444732965739290427391
; CHECK-NEXT:    [[IDX:%.*]] = add i128 [[I]], 1180591620717411303424
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr addrspace(100) [[BASE]], i128 [[IDX]]
; CHECK-NEXT:    ret ptr addrspace(100) [[GEP]]
;
  %base = getelementptr i8, ptr addrspace(100) %P, i128 -9444732965739290427391
  %idx = add i128 %i, 1180591620717411303424
  %gep = getelementptr double, ptr addrspace(100) %base, i128 %idx
  ret ptr addrspace(100) %gep
}

; Covers reorderGEP's nested GEP addressing mode check.
define ptr addrspace(100) @reorder_overwide_nested_offset(ptr addrspace(100) %P, i128 %i) {
; CHECK-LABEL: define ptr addrspace(100) @reorder_overwide_nested_offset(
; CHECK-SAME: ptr addrspace(100) [[P:%.*]], i128 [[I:%.*]]) {
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr double, ptr addrspace(100) [[P]], i128 1180591620717411303424
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr double, ptr addrspace(100) [[BASE]], i128 [[I]]
; CHECK-NEXT:    ret ptr addrspace(100) [[GEP]]
;
  %base = getelementptr double, ptr addrspace(100) %P, i128 1180591620717411303424
  %gep = getelementptr double, ptr addrspace(100) %base, i128 %i
  ret ptr addrspace(100) %gep
}
