; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -loop-reduce -S %s | FileCheck %s

target datalayout = "e-m:e-i64:64-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; LSR normalizes the post-increment use of %iv (the live-out value) as
; %iv = %iv.next - %step. This is structurally invertible, but introduces a
; new use of %step: when %step is poison, %iv.next - %step is poison even
; though the original %iv (0 on the path that exits the loop) is not. LSR must
; not perform this rewrite. See PR174200.
define i32 @pr174200(i32 %step) {
; CHECK-LABEL: define i32 @pr174200(
; CHECK-SAME: i32 [[STEP:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[M:%.*]] = and i32 [[IV]], 65535
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[M]], 8
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], [[STEP]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 [[IV]]
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %m = and i32 %iv, 65535
  %cmp = icmp sgt i32 %m, 8
  %iv.next = add i32 %iv, %step
  br i1 %cmp, label %loop, label %exit

exit:
  ret i32 %iv
}
