# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=amdgcn -mcpu=gfx942 --iterations=1 --timeline --timeline-max-cycles=0 < %s | FileCheck %s --check-prefix=GFX942
# RUN: llvm-mca -mtriple=amdgcn -mcpu=gfx950 --iterations=1 --timeline --timeline-max-cycles=0 < %s | FileCheck %s --check-prefix=GFX950

# Regression test for MIMFMARead removal on gfx942/gfx950. v_add_u32 writes
# v4 (latency 1) and v_mfma_f32_16x16x16_f16 reads v[4:5] as src0. While the
# MFMA had MIMFMARead attached, ReadAdvance=-4 turned that into a 5-cycle
# producer-to-MFMA edge; without it, the natural 1-cycle latency applies and
# the MFMA can issue immediately after the add.

v_add_u32_e32 v4, v5, v6
v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX942:      Iterations:        1
# GFX942-NEXT: Instructions:      2
# GFX942-NEXT: Total Cycles:      6
# GFX942-NEXT: Total uOps:        2

# GFX950:      Iterations:        1
# GFX950-NEXT: Instructions:      2
# GFX950-NEXT: Total Cycles:      6
# GFX950-NEXT: Total uOps:        2

# GFX942:      Dispatch Width:    1
# GFX942-NEXT: uOps Per Cycle:    0.33
# GFX942-NEXT: IPC:               0.33
# GFX942-NEXT: Block RThroughput: 4.0

# GFX950:      Dispatch Width:    1
# GFX950-NEXT: uOps Per Cycle:    0.33
# GFX950-NEXT: IPC:               0.33
# GFX950-NEXT: Block RThroughput: 4.0

# GFX942:      Instruction Info:
# GFX942-NEXT: [1]: #uOps
# GFX942-NEXT: [2]: Latency
# GFX942-NEXT: [3]: RThroughput
# GFX942-NEXT: [4]: MayLoad
# GFX942-NEXT: [5]: MayStore
# GFX942-NEXT: [6]: HasSideEffects (U)

# GFX950:      Instruction Info:
# GFX950-NEXT: [1]: #uOps
# GFX950-NEXT: [2]: Latency
# GFX950-NEXT: [3]: RThroughput
# GFX950-NEXT: [4]: MayLoad
# GFX950-NEXT: [5]: MayStore
# GFX950-NEXT: [6]: HasSideEffects (U)

# GFX942:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# GFX942-NEXT:  1      1     1.00                  U     v_add_u32_e32 v4, v5, v6
# GFX942-NEXT:  1      4     4.00                  U     v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX950:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# GFX950-NEXT:  1      1     1.00                  U     v_add_u32_e32 v4, v5, v6
# GFX950-NEXT:  1      4     4.00                  U     v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX942:      Resources:
# GFX942-NEXT: [0]   - HWBranch
# GFX942-NEXT: [1]   - HWExport
# GFX942-NEXT: [2]   - HWLGKM
# GFX942-NEXT: [3]   - HWSALU
# GFX942-NEXT: [4]   - HWVALU
# GFX942-NEXT: [5]   - HWVMEM
# GFX942-NEXT: [6]   - HWXDL

# GFX950:      Resources:
# GFX950-NEXT: [0]   - HWBranch
# GFX950-NEXT: [1]   - HWExport
# GFX950-NEXT: [2]   - HWLGKM
# GFX950-NEXT: [3]   - HWSALU
# GFX950-NEXT: [4]   - HWVALU
# GFX950-NEXT: [5]   - HWVMEM
# GFX950-NEXT: [6]   - HWXDL

# GFX942:      Resource pressure per iteration:
# GFX942-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]
# GFX942-NEXT:  -      -      -      -     1.00    -     4.00

# GFX950:      Resource pressure per iteration:
# GFX950-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]
# GFX950-NEXT:  -      -      -      -     1.00    -     4.00

# GFX942:      Resource pressure by instruction:
# GFX942-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# GFX942-NEXT:  -      -      -      -     1.00    -      -     v_add_u32_e32 v4, v5, v6
# GFX942-NEXT:  -      -      -      -      -      -     4.00   v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX950:      Resource pressure by instruction:
# GFX950-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# GFX950-NEXT:  -      -      -      -     1.00    -      -     v_add_u32_e32 v4, v5, v6
# GFX950-NEXT:  -      -      -      -      -      -     4.00   v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX942:      Timeline view:
# GFX942-NEXT: Index     012345

# GFX950:      Timeline view:
# GFX950-NEXT: Index     012345

# GFX942:      [0,0]     DE   .   v_add_u32_e32 v4, v5, v6
# GFX942-NEXT: [0,1]     .DeeeE   v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX950:      [0,0]     DE   .   v_add_u32_e32 v4, v5, v6
# GFX950-NEXT: [0,1]     .DeeeE   v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]

# GFX942:      Average Wait times (based on the timeline view):
# GFX942-NEXT: [0]: Executions
# GFX942-NEXT: [1]: Average time spent waiting in a scheduler's queue
# GFX942-NEXT: [2]: Average time spent waiting in a scheduler's queue while ready
# GFX942-NEXT: [3]: Average time elapsed from WB until retire stage

# GFX950:      Average Wait times (based on the timeline view):
# GFX950-NEXT: [0]: Executions
# GFX950-NEXT: [1]: Average time spent waiting in a scheduler's queue
# GFX950-NEXT: [2]: Average time spent waiting in a scheduler's queue while ready
# GFX950-NEXT: [3]: Average time elapsed from WB until retire stage

# GFX942:            [0]    [1]    [2]    [3]
# GFX942-NEXT: 0.     1     0.0    0.0    0.0       v_add_u32_e32 v4, v5, v6
# GFX942-NEXT: 1.     1     0.0    0.0    0.0       v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]
# GFX942-NEXT:        1     0.0    0.0    0.0       <total>

# GFX950:            [0]    [1]    [2]    [3]
# GFX950-NEXT: 0.     1     0.0    0.0    0.0       v_add_u32_e32 v4, v5, v6
# GFX950-NEXT: 1.     1     0.0    0.0    0.0       v_mfma_f32_16x16x16_f16 v[0:3], v[4:5], v[6:7], v[0:3]
# GFX950-NEXT:        1     0.0    0.0    0.0       <total>
