; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=indvars < %s | FileCheck %s

; A legal integer width is required for FindLoopCounter to pick an IV.
target datalayout = "n8:16:32:64"

@lftr_pointer_object = global [1 x i8] zeroinitializer

define i32 @duplicate_exit_cond(i32 %start, i32 %end, i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @duplicate_exit_cond(
; CHECK-SAME: i32 [[START:%.*]], i32 [[END:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GUARD:%.*]] = icmp slt i32 [[START]], [[END]]
; CHECK-NEXT:    br i1 [[GUARD]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], %[[LOOP]] ], [ [[START]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[SEL:%.*]], %[[LOOP]] ], [ [[A]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp slt i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    [[SEL]] = select i1 [[EXITCOND]], i32 [[B]], i32 [[V]]
; CHECK-NEXT:    [[EXITCOND1:%.*]] = icmp ne i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    br i1 [[EXITCOND1]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[LOOP]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[V_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %guard = icmp slt i32 %start, %end
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ %start, %entry ], [ %iv.next, %loop ]
  %v = phi i32 [ %a, %entry ], [ %sel, %loop ]
  %iv.next = add nsw i32 %iv, 1
  %cmp.dup = icmp slt i32 %iv.next, %end
  %sel = select i1 %cmp.dup, i32 %b, i32 %v
  %cmp.exit = icmp slt i32 %iv.next, %end
  br i1 %cmp.exit, label %loop, label %exit

exit:
  %r = phi i32 [ 0, %entry ], [ %v, %loop ]
  ret i32 %r
}

define i32 @shared_exit_cond(i32 %start, i32 %end, i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @shared_exit_cond(
; CHECK-SAME: i32 [[START:%.*]], i32 [[END:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GUARD:%.*]] = icmp slt i32 [[START]], [[END]]
; CHECK-NEXT:    br i1 [[GUARD]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], %[[LOOP]] ], [ [[START]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[SEL:%.*]], %[[LOOP]] ], [ [[A]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp slt i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    [[SEL]] = select i1 [[EXITCOND]], i32 [[B]], i32 [[V]]
; CHECK-NEXT:    [[EXITCOND1:%.*]] = icmp ne i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    br i1 [[EXITCOND1]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[LOOP]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[V_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %guard = icmp slt i32 %start, %end
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ %start, %entry ], [ %iv.next, %loop ]
  %v = phi i32 [ %a, %entry ], [ %sel, %loop ]
  %iv.next = add nsw i32 %iv, 1
  %cmp = icmp slt i32 %iv.next, %end
  %sel = select i1 %cmp, i32 %b, i32 %v
  br i1 %cmp, label %loop, label %exit

exit:
  %r = phi i32 [ 0, %entry ], [ %v, %loop ]
  ret i32 %r
}

define i32 @condition_before_increment(i32 %end, i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @condition_before_increment(
; CHECK-SAME: i32 [[END:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GUARD:%.*]] = icmp sgt i32 [[END]], 0
; CHECK-NEXT:    br i1 [[GUARD]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[END]], 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], %[[LOOP]] ], [ 0, %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[SEL:%.*]], %[[LOOP]] ], [ [[A]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp slt i32 [[IV]], [[END]]
; CHECK-NEXT:    [[SEL]] = select i1 [[EXITCOND]], i32 [[B]], i32 [[V]]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND1:%.*]] = icmp ne i32 [[IV_NEXT]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND1]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[LOOP]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[V_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %guard = icmp sgt i32 %end, 0
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %v = phi i32 [ %a, %entry ], [ %sel, %loop ]
  %cmp.dup = icmp slt i32 %iv, %end
  %sel = select i1 %cmp.dup, i32 %b, i32 %v
  %iv.next = add nsw i32 %iv, 1
  %cmp.exit = icmp slt i32 %iv, %end
  br i1 %cmp.exit, label %loop, label %exit

exit:
  %r = phi i32 [ 0, %entry ], [ %v, %loop ]
  ret i32 %r
}

define i32 @duplicate_exit_cond_in_loop_body(i32 %start, i32 %end, i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @duplicate_exit_cond_in_loop_body(
; CHECK-SAME: i32 [[START:%.*]], i32 [[END:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[GUARD:%.*]] = icmp slt i32 [[START]], [[END]]
; CHECK-NEXT:    br i1 [[GUARD]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; CHECK:       [[LOOP_PREHEADER]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ], [ [[START]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[SEL:%.*]], %[[LATCH]] ], [ [[A]], %[[LOOP_PREHEADER]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp slt i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    [[SEL]] = select i1 [[EXITCOND]], i32 [[B]], i32 [[V]]
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[EXITCOND1:%.*]] = icmp ne i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    br i1 [[EXITCOND1]], label %[[LOOP]], label %[[EXIT_LOOPEXIT:.*]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[LATCH]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[V_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %guard = icmp slt i32 %start, %end
  br i1 %guard, label %loop, label %exit

loop:
  %iv = phi i32 [ %start, %entry ], [ %iv.next, %latch ]
  %v = phi i32 [ %a, %entry ], [ %sel, %latch ]
  %iv.next = add nsw i32 %iv, 1
  %cmp.dup = icmp slt i32 %iv.next, %end
  %sel = select i1 %cmp.dup, i32 %b, i32 %v
  br label %latch

latch:
  %cmp.exit = icmp slt i32 %iv.next, %end
  br i1 %cmp.exit, label %loop, label %exit

exit:
  %r = phi i32 [ 0, %entry ], [ %v, %latch ]
  ret i32 %r
}

; The per-exit count relies on the exit controlling a finite loop. Computing
; an exit limit from the condition alone cannot make that assumption, so the
; duplicate condition must not be replaced.
define i32 @condition_only_not_analyzable(i32 %end, i32 %a, i32 %b) mustprogress {
; CHECK-LABEL: define i32 @condition_only_not_analyzable(
; CHECK-SAME: i32 [[END:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[UMAX:%.*]] = call i32 @llvm.umax.i32(i32 [[END]], i32 2)
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[UMAX]], -1
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[TMP0]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw i32 [[TMP1]], 1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[COUNTER:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[COUNTER_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[V:%.*]] = phi i32 [ [[A]], %[[ENTRY]] ], [ [[SEL:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i32 [[IV]], 2
; CHECK-NEXT:    [[COUNTER_NEXT]] = add nuw nsw i32 [[COUNTER]], 1
; CHECK-NEXT:    [[CMP_DUP:%.*]] = icmp ult i32 [[IV_NEXT]], [[END]]
; CHECK-NEXT:    [[SEL]] = select i1 [[CMP_DUP]], i32 [[B]], i32 [[V]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[COUNTER_NEXT]], [[TMP2]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i32 [ [[V]], %[[LOOP]] ]
; CHECK-NEXT:    ret i32 [[V_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  %counter = phi i32 [ 0, %entry ], [ %counter.next, %loop ]
  %v = phi i32 [ %a, %entry ], [ %sel, %loop ]
  %iv.next = add i32 %iv, 2
  %counter.next = add nuw i32 %counter, 1
  %cmp.dup = icmp ult i32 %iv.next, %end
  %sel = select i1 %cmp.dup, i32 %b, i32 %v
  %cmp.exit = icmp ult i32 %iv.next, %end
  br i1 %cmp.exit, label %loop, label %exit

exit:
  ret i32 %v
}

; The post-incremented pointer is poison, but that only causes UB along the
; path through the latch. The alternate exit remains well-defined, so the
; pointer-based LFTR comparison must not replace the duplicate condition there.
define i32 @pointer_counter_with_alternate_exit(i1 %early) {
; CHECK-LABEL: define i32 @pointer_counter_with_alternate_exit(
; CHECK-SAME: i1 [[EARLY:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[PTR_IV:%.*]] = phi ptr [ getelementptr inbounds ([1 x i8], ptr @lftr_pointer_object, i64 0, i64 1), %[[ENTRY]] ], [ [[PTR_IV_NEXT:%.*]], %[[LATCH]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i32 [[IV]], 2
; CHECK-NEXT:    [[PTR_IV_NEXT]] = getelementptr inbounds i8, ptr [[PTR_IV]], i64 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp samesign ult i32 [[IV_NEXT]], 10
; CHECK-NEXT:    [[SEL:%.*]] = select i1 [[EXITCOND]], i32 1, i32 2
; CHECK-NEXT:    br i1 [[EARLY]], label %[[ALTERNATE_EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[VALUE:%.*]] = load volatile i8, ptr [[PTR_IV_NEXT]], align 1
; CHECK-NEXT:    [[EXITCOND1:%.*]] = icmp ne ptr [[PTR_IV_NEXT]], getelementptr (i8, ptr @lftr_pointer_object, i64 6)
; CHECK-NEXT:    br i1 [[EXITCOND1]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[ALTERNATE_EXIT]]:
; CHECK-NEXT:    [[SEL_LCSSA:%.*]] = phi i32 [ [[SEL]], %[[LOOP]] ]
; CHECK-NEXT:    ret i32 [[SEL_LCSSA]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %ptr.iv = phi ptr [ getelementptr inbounds ([1 x i8], ptr @lftr_pointer_object, i64 0, i64 1), %entry ], [ %ptr.iv.next, %latch ]
  %iv.next = add nuw nsw i32 %iv, 2
  %ptr.iv.next = getelementptr inbounds i8, ptr %ptr.iv, i64 1
  %cmp.dup = icmp slt i32 %iv.next, 10
  %sel = select i1 %cmp.dup, i32 1, i32 2
  br i1 %early, label %alternate.exit, label %latch

latch:
  %value = load volatile i8, ptr %ptr.iv.next
  %cmp.exit = icmp slt i32 %iv.next, 10
  br i1 %cmp.exit, label %loop, label %exit

alternate.exit:
  ret i32 %sel

exit:
  ret i32 0
}
